rebrand
ipbc-dev/BitTubeVid pull request #1
Opened 2020-02-20 16:59 UTC by dailosu

2020-02-20 17:35 UTC, cabaleiro8 requested changes
Accept changes and I will merge. Thanks!

2020-02-20 17:35 UTC, cabaleiro8 commented on FAQ.md
> +- [Why did you create BitTu?](#why-did-you-create-BitTube)
BitTu -> BitTube
```suggestion
- [Why did you create BitTube?](#why-did-you-create-BitTube)
```

2020-02-20 17:35 UTC, cabaleiro8 commented on FAQ.md
>  ## Why host on GitHub and Framagit?
Remove Framagit
```suggestion
## Why host on GitHub?
```

2020-02-20 17:35 UTC, cabaleiro8 commented on FAQ.md
> +The project has initially been hosted on GitHub by ipbc-dev.
```suggestion
The project has initially been hosted on GitHub by ipbc-dev. We will keep it here as it is more accesible to everybody.
```

2020-02-21 12:34 UTC, cabaleiro8 approved these changes

2020-02-21 12:35 UTC, merged

2020-04-20 10:13 UTC, DontUseGithub commented
Hi Bittube devs!

I have a few things to tell you:
-I saw that you're building mobile apps, have you considered forking and rebranding Thorium? It's a great android client for Peertube/Bittube.
-Do you plan to transition bittube.tv to your peertube-based Bittube? When do you plan to do this? Thanks
-Have you considered using GitLab or [Framagit](https://framagit.org)? Github isn't very open source friendly.